### ISSUE TITLE
Publish 0.1.19 on npm

### ISSUE THREAD

**Issue by tlvince** [shahata/google-cdn-data#30]
The latest version on npm is [0.1.17](https://www.npmjs.com/package/google-cdn-data). Could you publish 0.1.19 (and 0.1.18)? NB, you might like to integrate https://www.npmjs.com/package/semantic-release

**Comment by passy** [comment]
// @shahata

**Comment by redwood-egarcea** [comment]
+1

**Comment by scatcher** [comment]
+1

**Comment by shahata** [comment]
Done. Sorry for the delay :(
