### ISSUE TITLE
Publish 0.1.24 to npm

### ISSUE THREAD

**Issue by junglebarry** [shahata/google-cdn-data#41]
Hi,

Sorry to bother you with this.  I hope I've come to the right place.

This package here states that it has [a release for 0.1.24](https://github.com/shahata/google-cdn-data/releases/tag/0.1.24), but when I attempted to download it from npm I discovered that [the latest version listed there is 0.1.23](https://www.npmjs.com/package/google-cdn-data).

Please could you republish 0.1.24 to npm?

Many thanks!
David

**Comment by shahata** [comment]
released 0.1.25
